-- Generated by the Organizer Library (03/09/17 17:58:54)
return {
    [1]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Accuracy+25", 
            [2]="\"Triple Atk.\"+4", 
            [3]="Attack+7"
        }
    }, 
    [2]={
        ["log_name"]="passion jacket", 
        ["id"]=25727, 
        ["name"]="passion jacket", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="choreia earring", 
        ["id"]=16055, 
        ["name"]="choreia earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="dampening tam", 
        ["count"]=1, 
        ["id"]=25630, 
        ["name"]="dampening tam", 
        ["augments"]={
            [1]="DEX+9", 
            [2]="Accuracy+13", 
            [3]="Mag. Acc.+14", 
            [4]="Quadruple Attack +2"
        }
    }, 
    [7]={
        ["log_name"]="dread jupon", 
        ["id"]=27858, 
        ["name"]="dread jupon", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="mekosuchinae harness", 
        ["id"]=27856, 
        ["name"]="mekosu. harness", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="xucau mantle", 
        ["id"]=27614, 
        ["name"]="xucau mantle", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="adhemar jacket", 
        ["count"]=1, 
        ["id"]=25686, 
        ["name"]="adhemar jacket", 
        ["augments"]={
            [1]="DEX+10", 
            [2]="AGI+10", 
            [3]="Accuracy+15"
        }
    }, 
    [11]={
        ["log_name"]="herculean vest", 
        ["count"]=1, 
        ["id"]=25718, 
        ["name"]="herculean vest", 
        ["augments"]={
            [1]="Accuracy+3 Attack+3", 
            [2]="Crit. hit damage +4%", 
            [3]="DEX+9", 
            [4]="Accuracy+7", 
            [5]="Attack+1"
        }
    }, 
    [12]={
        ["log_name"]="chaac belt", 
        ["id"]=28450, 
        ["name"]="chaac belt", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="herculean trousers", 
        ["count"]=1, 
        ["id"]=25842, 
        ["name"]="herculean trousers", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Crit. hit damage +3%", 
            [3]="DEX+6", 
            [4]="Attack+3"
        }
    }, 
    [14]={
        ["log_name"]="leyline gloves", 
        ["count"]=1, 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+15", 
            [3]="\"Mag.Atk.Bns.\"+15", 
            [4]="\"Fast Cast\"+3"
        }
    }, 
    [15]={
        ["log_name"]="adhemar bonnet", 
        ["count"]=1, 
        ["id"]=25613, 
        ["name"]="adhemar bonnet", 
        ["augments"]={
            [1]="DEX+10", 
            [2]="AGI+10", 
            [3]="Accuracy+15"
        }
    }, 
    [16]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Accuracy+23 Attack+23", 
            [2]="Crit. hit damage +3%", 
            [3]="STR+8", 
            [4]="Attack+15"
        }
    }, 
    [17]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Accuracy+21 Attack+21", 
            [2]="\"Triple Atk.\"+3", 
            [3]="STR+9", 
            [4]="Accuracy+15", 
            [5]="Attack+9"
        }
    }, 
    [18]={
        ["log_name"]="samnuha tights", 
        ["count"]=1, 
        ["id"]=27295, 
        ["name"]="samnuha tights", 
        ["augments"]={
            [1]="STR+8", 
            [2]="DEX+9", 
            [3]="\"Dbl.Atk.\"+3", 
            [4]="\"Triple Atk.\"+2"
        }
    }
}