-- Generated by the Organizer Library (01/16/17 20:14:18)
return {
    [1]={
        ["log_name"]="samnuha tights", 
        ["id"]=27295, 
        ["name"]="samnuha tights", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="passion jacket", 
        ["id"]=25727, 
        ["name"]="passion jacket", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="skadi's jambeaux +1", 
        ["id"]=28209, 
        ["name"]="skd. jambeaux +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="begrudging ring", 
        ["id"]=26172, 
        ["name"]="begrudging ring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="adhemar jacket", 
        ["id"]=25686, 
        ["name"]="adhemar jacket", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="dampening tam", 
        ["count"]=1, 
        ["id"]=25630, 
        ["name"]="dampening tam", 
        ["augments"]={
            [1]="DEX+9", 
            [2]="Accuracy+13", 
            [3]="Mag. Acc.+14", 
            [4]="Quadruple Attack +2"
        }
    }, 
    [8]={
        ["log_name"]="dread jupon", 
        ["id"]=27858, 
        ["name"]="dread jupon", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="herculean trousers", 
        ["id"]=25842, 
        ["name"]="herculean trousers", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="samnuha coat", 
        ["id"]=26973, 
        ["name"]="samnuha coat", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="leyline gloves", 
        ["count"]=1, 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+15", 
            [3]="\"Mag.Atk.Bns.\"+15", 
            [4]="\"Fast Cast\"+3"
        }
    }, 
    [13]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="AGI+7", 
            [2]="Crit.hit rate+1", 
            [3]="\"Refresh\"+2", 
            [4]="Accuracy+5 Attack+5", 
            [5]="Mag. Acc.+9 \"Mag.Atk.Bns.\"+9"
        }
    }, 
    [14]={
        ["log_name"]="jukukik feather", 
        ["id"]=21386, 
        ["name"]="jukukik feather", 
        ["count"]=1
    }
}