-- Generated by the Organizer Library (03/09/17 17:58:54)
return {
    [1]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="bleating mantle", 
        ["id"]=27600, 
        ["name"]="bleating mantle", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="mecistopins mantle", 
        ["id"]=27596, 
        ["name"]="mecisto. mantle", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="epona's ring", 
        ["id"]=11651, 
        ["name"]="epona's ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="paguroidea ring", 
        ["id"]=10753, 
        ["name"]="paguroidea ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="impatiens", 
        ["id"]=19761, 
        ["name"]="impatiens", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="hetairoi ring", 
        ["id"]=26175, 
        ["name"]="hetairoi ring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+4", 
            [2]="TP Bonus +25"
        }
    }, 
    [16]={
        ["log_name"]="clotharius torque", 
        ["id"]=26017, 
        ["name"]="clotharius torque", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="windbuffet belt +1", 
        ["id"]=28440, 
        ["name"]="windbuffet belt +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="vanir battery", 
        ["id"]=21380, 
        ["name"]="vanir battery", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }
}