-- Generated by the Organizer Library (03/09/17 17:58:54)
return {
    [1]={
        ["log_name"]="magoraga bead necklace", 
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="happo shuriken", 
        ["id"]=21353, 
        ["name"]="happo shuriken", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="andartia's mantle", 
        ["count"]=1, 
        ["id"]=26258, 
        ["name"]="andartia's mantle", 
        ["augments"]={
            [1]="AGI+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="Weapon skill damage +10%"
        }
    }
}