-- Generated by the Organizer Library (01/16/17 20:14:18)
return {
    [1]={
        ["log_name"]="magoraga bead necklace", 
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1
    }
}