-- Generated by the Organizer Library (01/16/17 20:14:18)
return {
    [1]={
        ["log_name"]="kurys gloves", 
        ["id"]=27134, 
        ["name"]="kurys gloves", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="aqreaqa bomblet", 
        ["id"]=21385, 
        ["name"]="aqreqaq bomblet", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="taeon boots", 
        ["count"]=1, 
        ["id"]=27404, 
        ["name"]="taeon boots", 
        ["augments"]={
            [1]="Accuracy+9 Attack+9", 
            [2]="\"Triple Atk.\"+1", 
            [3]="Crit. hit damage +2%"
        }
    }, 
    [4]={
        ["log_name"]="grenade core", 
        ["id"]=22251, 
        ["name"]="grenade core", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="highwing helm", 
        ["id"]=26716, 
        ["name"]="highwing helm", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="demonry stone", 
        ["id"]=19765, 
        ["name"]="demonry stone", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="subtlety spectacles", 
        ["id"]=27513, 
        ["name"]="subtlety spec.", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="orvail pants +1", 
        ["id"]=28184, 
        ["name"]="orvail pants +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="unmoving collar", 
        ["id"]=27508, 
        ["name"]="unmoving collar", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="mubvumbamiri mantle", 
        ["id"]=28604, 
        ["name"]="mubvum. mantle", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="evasionist's cape", 
        ["count"]=1, 
        ["id"]=28638, 
        ["name"]="evasionist's cape", 
        ["augments"]={
            [1]="Enmity+2", 
            [2]="\"Embolden\"+14", 
            [3]="\"Dbl.Atk.\"+1", 
            [4]="Damage taken-4%"
        }
    }, 
    [12]={
        ["id"]=28546, 
        ["name"]="capacity ring", 
        ["count"]=1, 
        ["log_name"]="capacity ring"
    }, 
    [13]={
        ["id"]=20761, 
        ["name"]="aettir", 
        ["count"]=1, 
        ["log_name"]="aettir"
    }, 
    [14]={
        ["id"]=21415, 
        ["name"]="forefathers' grip", 
        ["count"]=1, 
        ["log_name"]="forefathers' grip"
    }, 
    [15]={
        ["id"]=4151, 
        ["name"]="echo drops", 
        ["count"]=12, 
        ["log_name"]="flask of echo drops"
    }, 
    [16]={
        ["id"]=1179, 
        ["name"]="shihei", 
        ["count"]=99, 
        ["log_name"]="shihei"
    }
}