-- Generated by the Organizer Library (03/09/17 17:58:54)
return {
    [1]={
        ["id"]=5867, 
        ["name"]="toolbag (ino)", 
        ["count"]=12, 
        ["log_name"]="toolbag (inoshishinofuda)"
    }, 
    [2]={
        ["id"]=5869, 
        ["name"]="toolbag (cho)", 
        ["count"]=12, 
        ["log_name"]="toolbag (chonofuda)"
    }, 
    [3]={
        ["id"]=5868, 
        ["name"]="toolbag (shika)", 
        ["count"]=12, 
        ["log_name"]="toolbag (shikanofuda)"
    }, 
    [4]={
        ["id"]=21353, 
        ["name"]="happo shuriken", 
        ["count"]=99, 
        ["log_name"]="happo shuriken"
    }, 
    [5]={
        ["id"]=28546, 
        ["name"]="capacity ring", 
        ["count"]=1, 
        ["log_name"]="capacity ring"
    }, 
    [6]={
        ["id"]=2973, 
        ["name"]="chonofuda", 
        ["count"]=99, 
        ["log_name"]="chonofuda"
    }, 
    [7]={
        ["id"]=6306, 
        ["name"]="hap. sh. pouch", 
        ["count"]=12, 
        ["log_name"]="happo shuriken pouch"
    }, 
    [8]={
        ["id"]=2972, 
        ["name"]="shikanofuda", 
        ["count"]=99, 
        ["log_name"]="shikanofuda"
    }, 
    [9]={
        ["id"]=4151, 
        ["name"]="echo drops", 
        ["count"]=12, 
        ["log_name"]="flask of echo drops"
    }, 
    [10]={
        ["id"]=26165, 
        ["name"]="facility ring", 
        ["count"]=1, 
        ["log_name"]="facility ring"
    }
}