-- Generated by the Organizer Library (02/19/17 11:39:57)
return {
    [1]={
        ["log_name"]="asklepian ring", 
        ["id"]=10787, 
        ["name"]="asklepian ring", 
        ["count"]=1
    }
}