-- Generated by the Organizer Library (03/09/17 17:58:54)
return {
    [1]={
        ["log_name"]="mochizuki chainmail", 
        ["id"]=26824, 
        ["name"]="mochi. chainmail", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Accuracy+24", 
            [2]="Weapon skill damage +2%", 
            [3]="AGI+9", 
            [4]="Attack+12"
        }
    }, 
    [3]={
        ["log_name"]="kurys gloves", 
        ["id"]=27134, 
        ["name"]="kurys gloves", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="amm greaves", 
        ["count"]=1, 
        ["id"]=27491, 
        ["name"]="amm greaves", 
        ["augments"]={
            [1]="HP+50", 
            [2]="VIT+10", 
            [3]="Accuracy+15", 
            [4]="Damage taken-2%"
        }
    }, 
    [5]={
        ["log_name"]="kanaria", 
        ["count"]=1, 
        ["id"]=21904, 
        ["name"]="kanaria", 
        ["augments"]={
            [1]="\"Triple Atk.\"+2", 
            [2]="DEX+4", 
            [3]="Accuracy+23", 
            [4]="Attack+19", 
            [5]="DMG:+14"
        }
    }, 
    [6]={
        ["log_name"]="kanaria", 
        ["count"]=1, 
        ["id"]=21904, 
        ["name"]="kanaria", 
        ["augments"]={
            [1]="Phys. dmg. taken -1%", 
            [2]="STR+1", 
            [3]="Accuracy+17", 
            [4]="Attack+2", 
            [5]="DMG:+20"
        }
    }, 
    [7]={
        ["log_name"]="ninjutsu torque", 
        ["id"]=13159, 
        ["name"]="ninjutsu torque", 
        ["count"]=1
    }
}